[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl:latest"
run-image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl:latest"
xargo = false

env = { RUSTFLAGS = "-L /libpq_layer/lib -C link-arg=-lpq -C link-arg=-lssl -C link-arg=-lcrypto -C link-arg=-lz -C link-arg=-static" }

volumes = [
  "libpq_layer:/libpq_layer"
]
